### PR TITLE
Probably want to remove your username from the file

### PR DESCRIPTION
**Pull request by hlesesne**

### CODE REVIEW

**Comment by hlesesne** [comment]
.. and this is a fantastic use case for IPFS. Thanks for doing it.

**Comment by PR0M3TH3AN** [comment]
Will do! I'm relatively new to this GitHub thing so bear with me. Thanks!

**Comment by hlesesne** [comment]
Thanks!. I notice that there isn't really a way to contact you from the site (which is probably by design) or your github profile, but I'd love to connect about this project. Please feel free to reach out to me through my profile email or a twitter dm (also on my profile). I just had a couple of questions.

**Comment by PR0M3TH3AN** [comment]
Sure! I have made a twitter account for the site and added a link to it in the websites footer. (in the github code) I'll push the update out to IPFS soon. You can contact me on that twitter account @EternalwordE or via email at thepr0m3th3an@protonmail.com.

**Pull request merged**
